# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
name: Publish plugin
on:
  release:
    types: published
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn package
      - name: Rename plugin with version number
        run: mv ./target/matlab-plugin.zip ./target/matlab-teamcity-plugin-${{ github.event.release.tag_name }}.zip
      - name: Upload release asset
        run: |
          gh release upload ${{ github.event.release.tag_name }} target/matlab-teamcity-plugin-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ github.token }}
